### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by phated** [tj/node-only#13]
Hey @tj!

I'd love to get this package updated on npm so it has SPDX license metadata. Would you be willing to add me or @tunnckoCore as a maintainer?

Cheers and hope all the Apex stuff is going great!
-Blaine

**Comment by tunnckoCore** [comment]
hey there @phated, i was out last few months, not active at all... are we added or just you?

**Comment by phated** [comment]
@tunnckoCore no one was added and I don't think TJ is looking at notifications.
